
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "../components/layouts/Navbar";
import Footer from "../components/layouts/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({ children }) {
  return (
    <div className="container mx-auto flex flex-col min-h-full">
      <Navbar />
      {children}
      <Footer />
    </div>
  );
}
